services:
  - type: worker
    name: telegram-media-bot
    env: python
    repo: https://github.com/akmalrad-123/telegram-media-bot_new
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py

