services:
  - type: web
    name: telegram-media-bot
    env: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: TZ
        value: Asia/Tashkent
